############################################################
# Draw the active components of the detector.
#

# Get the default values for the MC.
/dsim/control baseline 1.0

# Update the geometry so that the MC geometry is self consistent.
/dsim/update

/vis/open RayTracer 300x300

/vis/rayTracer/target 0 0 0 mm
/vis/rayTracer/eyePosition -5 0 0 m
/vis/rayTracer/headAngle 90 deg
/vis/rayTracer/span 7 deg
/vis/rayTracer/trace captain.jpg

