#!/bin/bash

# An example of a script using captain-control to generate lansce beam
# events in miniCAPTAIN.  This is actually pretty convenient to run
# from the command line.

source captain-control.bash

# Set the run number from the command line.
if [ ${#1} = 0 ]; then
    echo "Usage: $0 <run-number> <events>"
    captain-error "The run number must be provided."
fi

# Set the file name fields.
captain-experiment nb
captain-data-source pg
captain-run-type beam
captain-run-number ${1}
captain-processing-comment medium

DETSIM_MACRO=$(captain-file g4in)
cat <<EOF >> ${DETSIM_MACRO} 
# Make sure to use a new seed.
/dsim/random/timeRandomSeed

# Run this in mini-captain
/dsim/control mini-captain 1.0

# Update the simulated geometry.
/dsim/update

####################################################################
# Define the LANCE neutron beam based on data from October 2013.
####################################################################

/gps/particle neutron
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre -400. 0. -15. cm
/gps/pos/radius 5. mm
/gps/pos/sigma_r 0.1 mm

/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 1 0
/gps/ang/type beam1d
/gps/ene/type User
#using Flux_23-25_8_13_FP15R default unit for energy is MeV in GPS
/gps/ene/min 50 MeV
/gps/ene/max 800 MeV
/gps/hist/type energy
/gps/hist/point 50. 4.67E5
/gps/hist/point 55. 4.21E5
/gps/hist/point 60. 4.33E5
/gps/hist/point 70. 3.95E5
/gps/hist/point 80. 3.48E5
/gps/hist/point 90. 3.25E5
/gps/hist/point 100. 3.03E5
/gps/hist/point 125. 2.69E5
/gps/hist/point 150. 2.45E5
/gps/hist/point 175. 2.18E5
/gps/hist/point 200. 2.0E5
/gps/hist/point 225. 1.84E5
/gps/hist/point 250. 1.72E5
/gps/hist/point 275. 1.62E5
/gps/hist/point 300. 1.56E5
/gps/hist/point 350. 1.54E5
/gps/hist/point 400. 1.31E5
/gps/hist/point 450. 1.13E5
/gps/hist/point 500. 9.81E4
/gps/hist/point 550. 9.77E4
/gps/hist/point 600. 9.56E4
/gps/hist/point 800. 2.82E4
EOF

# Check if the number of events to generate should be added to the file.
if [ ${#2} = 0 ]; then
    echo "Usage: $0 <run-number> <events>"
    captain-error "The number of events must be provided"
else
    captain-log Generating ${2} events.
    cat >> ${DETSIM_MACRO} <<EOF
/run/beamOn ${2}
EOF
fi

#####################################################
# The is the meat of the script: Run the DETSIM
#####################################################
captain-process-detsim-macro ${DETSIM_MACRO}

#####################################################
# Try to run ELECSIM, calibration, and reconstruction.
#####################################################
captain-run-reconstruction
