# The default configuration file for the energy deposition simulation.
# This sets up the "usual" defaults for that detector and should be
# included any macro files.  This is loaded by the edep-sim main program
# compiled from app/edepSim.cc.  It can also be explicitly included using:

# /edep/control edepsim-defaults 1.0

/control/verbose 2

##############################################
# Define the default GEANT parameter settings
##############################################
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

##############################################
# Set the thresholds for saving trajectories into the output file.  All
# primary particle trajectories are saved so these only apply to secondary
# particles.  Energy that is deposited by unsaved secondaries is "assigned"
# to the "nearest" parent particle.
##############################################
/edep/db/set/saveAllPrimTraj true
/edep/db/set/lengthThreshold 1 mm
/edep/db/set/trajectoryAccuracy 1 mm
/edep/db/set/neutronThreshold 50 MeV
/edep/db/set/gammaThreshold 10 MeV

##############################################
# Set any physics limits.
##############################################

# Set the default ionization model.  The choices are 0) NEST which is slow,
# general, and accurate, 1) DokeBirks which is about 200 times faster
# than NEST, but only applicable to LAr (code stolen from NEST).
/edep/phys/ionizationModel 1
