############################################################
# Baseline conditions for the mini-CAPTAIN TPC.
#
# This sets the default detSim geometry.
#
# This is loaded using the /dsim/control directive.
#
# mini-CAPTAIN has 996 wires (332 wires per plane).
#
############################################################

/Captain/Cryostat/innerDiameter 1497 mm
/Captain/Cryostat/innerHeight 1080 mm
/Captain/Cryostat/argonDepth 845 mm

/Captain/Cryostat/Drift/apothem 503 mm
/Captain/Cryostat/Drift/driftLength 320 mm

/Captain/Cryostat/Drift/GridPlane/maxWireCount 332
/Captain/Cryostat/Drift/UPlane/maxWireCount 332
/Captain/Cryostat/Drift/VPlane/maxWireCount 332
/Captain/Cryostat/Drift/XPlane/maxWireCount 332
/Captain/Cryostat/Drift/GroundPlane/maxWireCount 332
