############################################################
# Baseline conditions for the mini-CAPTAIN TPC.
#
# This sets the default detSim geometry.
#
# This is loaded using the /dsim/control directive.
#
############################################################

/Captain/Cryostat/innerDiameter 1497 mm
/Captain/Cryostat/innerHeight 1080 mm
/Captain/Cryostat/argonDepth 845 mm

/Captain/Cryostat/Drift/apothem 500 mm
/Captain/Cryostat/Drift/driftLength 320 mm
